### ISSUE TITLE
Build error on Debian 11

### ISSUE THREAD

**Issue by radiden** [lambertjamesd/skelatool64#1]
Hello! I'm trying to make a docker container for building portal64, but I ran into this error while building:

```
src/BoneHierarchy.cpp: In member function 'std::unique_ptr<DataChunk> Bone::GenerateRestPosiitonData(float, const aiQuaternion&)':
src/BoneHierarchy.cpp:31:60: error: passing 'const aiQuaternion' {aka 'const aiQuaterniont<float>'} as 'this' argument discards qualifiers [-fpermissive]
   31 |     aiVector3D restPosition = rotation.Rotate(mRestPosition);
      |                                                            ^
In file included from /usr/include/assimp/types.h:537,
                 from /usr/include/assimp/scene.h:51,
                 from src/BoneHierarchy.h:6,
                 from src/BoneHierarchy.cpp:2:
/usr/include/assimp/quaternion.inl:276:26: note:   in call to 'aiVector3t<TReal> aiQuaterniont<TReal>::Rotate(const aiVector3t<TReal>&) [with TReal = float]'
  276 | inline aiVector3t<TReal> aiQuaterniont<TReal>::Rotate (const aiVector3t<TReal>& v)
      |                          ^~~~~~~~~~~~~~~~~~~~
make: *** [makefile:19: build/src/BoneHierarchy.o] Error 1
```

**Comment by lambertjamesd** [comment]
What version of gcc are you using?

**Comment by lambertjamesd** [comment]
Do you have a branch you are working on for adding the dockerfile? I could try building the docker image on my machine to see if it replicates the error

**Comment by radiden** [comment]
`gcc version 10.2.1 20210110 (Debian 10.2.1-6)`

Branch with dockerfile can be found here: https://github.com/radiden/portal64/tree/docker-build

**Comment by lambertjamesd** [comment]
I will take a look at this later, in the meantime I added an apt repo and instructions in the readme on how to download that

**Comment by lambertjamesd** [comment]
I pushed a fix and Dockerfile you can use a reference to get skeletool building in the portal64 project. I plan on just bundling skeletool as part of the same repo as portal64 during development so I don't have to worry version mismatch going forward.
